### ISSUE TITLE
Name of operators to get a field value

### ISSUE THREAD

**Issue by samuel1992** [samuel1992/payload-translator#4]
What could be a better name than `GetField`, `GetSubField` and `GetFieldFromList`??
I thought about  in using `GetFrom` and maybe just declare as a parameter `sub_field=True`, `list=True`. But I dont know. If you have an ideia for a better name, comment here.

**Comment by iagocavalcante** [comment]
I think GetFrom, GetFromChild and GetFromList could be a better nomenclature. I preffer separeted methods to specif scopes.

**Comment by samuel1992** [comment]
Awesome! I agree with you for keeping it separated. Im just thinking in merge the `GetFrom` and the `GetFromChild`.
